### PR TITLE
Several fixes to v4 modules settings documentation

### PR DESCRIPTION
**Pull request by ralish**
Just a bunch of relatively minor fixes to the modules documentation for InspIRCd v4 I found while upgrading a server from v3.

### CODE REVIEW

**Comment by SadieCat** [comment]
Other than the one change I mentioned I think this LGTM. I'll merge it later once I have a chance to check whether any of these changes need to be backported to the v3 docs.

**Comment by ralish** [comment]
I've added a commit that updates the default for the `duration` setting of the `ircv3_sts` module as well as some explanatory text on why it's so low and when to raise it.

**Comment by SadieCat** [comment]
Merged with some minor edits, thanks for your contribution! :saluting_face:

**Comment by ralish** [comment]
Glad to help, it's a great project. I just wish IRC had more adoption, but that's a philosophical question. :)

**Pull request merged**
